name: Update Docker Hub description and README

on:
  push:
    paths:
      - README.md   # Changes on README.md updates Docker Hub description and README

jobs:

  docker-description:
    name: Update Docker Hub description and README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Docker Hub description and README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          repository: afonsoc12/firefly-cli
